/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_engine_physics_PhysicsEngine */

#ifndef _Included_com_engine_physics_PhysicsEngine
#define _Included_com_engine_physics_PhysicsEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef com_engine_physics_PhysicsEngine_rho
#define com_engine_physics_PhysicsEngine_rho 0.02
#undef com_engine_physics_PhysicsEngine_g
#define com_engine_physics_PhysicsEngine_g 0.163f
/*
 * Class:     com_engine_physics_PhysicsEngine
 * Method:    isIntersection
 * Signature: ([F[F[F[F[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_engine_physics_PhysicsEngine_isIntersection
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
